import pyautogui as aut

aut.press("win")
aut.sleep(1)
aut.write("chrome")
aut.press("enter")
aut.sleep(3)
aut.write("gmail.com")
aut.press("enter")
aut.sleep(3)
aut.moveTo(84,194)
aut.click()
aut.sleep(1)
aut.write("ricardo.rlima@sp.senai.br")
aut.press("enter")
aut.sleep(0.5)
aut.moveTo(1292,520)
aut.click()
aut.sleep(0.5)
aut.write("tá feito")
aut.sleep(0.5)
aut.moveTo(1460,666)
aut.click()
aut.write("26 linhas apenas de código")
aut.sleep(0.5)
aut.moveTo(1300,998)
aut.click()
